Ldca 413
eegeo/eegeo-example-app pull request #39
Opened 2016-12-21 14:47 UTC by najhiullah

Move Senion Android from SWP to eeGeo Example App

2016-12-21 14:56 UTC, tim-jenks requested changes
Only a partial review.

1. Please remove redundant 'avatar' assets on Android, may also exist on IOS

2. Please move Indoor Positioning Types to ExampleApp::IPS:: namespace

Will review again more thoroughly when this change is an isolated Senion change, not interleaved with the IndoorAtlas change.

This change seems to contain both significant additions to IndoorAtlas and Senion. Suggest we submit a single Senion PR when IndoorAtlas has been accepted.

2016-12-21 14:56 UTC, tim-jenks commented on android/AndroidManifest.xml
> +	<uses-permission android:name="android.permission.READ_PHONE_STATE" />
Required?

2016-12-21 14:56 UTC, tim-jenks commented on android/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.VIBRATE" />
Required?

2016-12-21 14:56 UTC, tim-jenks commented on android/AndroidManifest.xml
> +   	<uses-permission android:name="android.permission.WAKE_LOCK" />
Required?

2016-12-21 14:56 UTC, tim-jenks commented on android/jni/AppHost.h
> +    ExampleApp::IndoorAtlas::IndoorAtlasLocationModule* m_pIndoorAtlasLocationModule;
Can we move IA and Senion to ExampleApp::IPS:: to prevent namespace pollution

2020-07-09 10:31 UTC, SirPryderi commented
Outdated -- closing.

2020-07-09 10:31 UTC, closed without merging